# Generated by Django 4.2 on 2023-05-08 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_alter_meallog_date_favouriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 8, 19, 53, 44, 508501, tzinfo=datetime.timezone.utc)),
        ),
    ]
