# Generated by Django 4.2 on 2023-05-21 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0008_rename_shoppingproducts_shoppingproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingproduct',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 20, 3, 39, 372547, tzinfo=datetime.timezone.utc)),
        ),
    ]
