# Generated by Django 4.2 on 2023-05-22 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_shoppingproduct_amount_alter_meallog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='No description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 13, 9, 37, 211692, tzinfo=datetime.timezone.utc)),
        ),
    ]
