# Generated by Django 4.2 on 2023-06-18 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0012_alter_meallog_date_alter_recipedetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 13, 37, 9, 761595, tzinfo=datetime.timezone.utc)),
        ),
    ]
