# Generated by Django 4.2 on 2023-04-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
