# Generated by Django 4.2 on 2023-04-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
