# Generated by Django 4.2 on 2023-04-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_activity_level_profile_age_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'No physical activity'), (1.4, 'Low physical activity (140 minutes per week)'), (1.6, 'Medium physical activity (280 minutes per week)'), (1.8, 'High physical activity (420 minutes per week)'), (2.0, 'Very high physical activity (560 minutes per week)')], default=1.2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=10),
        ),
    ]
